### ISSUE TITLE
Constructor parameter should be str

### ISSUE THREAD

**Issue by Lexus083** [DogsTailFarmer/martin-binance#66]
Windows 10
Python 3.10

[2023-09-12 11:42:01,199: DEBUG] Using proactor: IocpProactor
[2023-09-12 11:42:03,254: DEBUG] Using AsyncIOEngine.POLLER as I/O engine
[2023-09-12 11:42:03,260: INFO] Starting server v:1.3.6 on localhost:50051
[2023-09-12 11:46:20,592: INFO] OpenClientConnection start trade: Binance:ZHggYy9NtfPQCuA73FZbGP
[2023-09-12 11:46:21,574: ERROR] Task exception was never retrieved
future: <Task finished name='Task-9' coro=<UserWSS.get_ws() done, defined at C:\Users\-\AppData\Local\Programs\Python\Python310\lib\site-packages\crypto_ws_api\ws_session.py:87> exception=TypeError('Constructor parameter should be str')>
Traceback (most recent call last):
  File "C:\Users\-\AppData\Local\Programs\Python\Python310\lib\site-packages\crypto_ws_api\ws_session.py", line 89, in get_ws
    await self._start_wss()
  File "C:\Users\-\AppData\Local\Programs\Python\Python310\lib\site-packages\crypto_ws_api\ws_session.py", line 120, in _start_wss
    self._ws = await self.session.ws_connect(
  File "C:\Users\-\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 779, in _ws_connect
    resp = await self.request(
  File "C:\Users\-\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 423, in _request
    url = self._build_url(str_or_url)
  File "C:\Users\-\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 357, in _build_url
    url = URL(str_or_url)
  File "C:\Users\-\AppData\Local\Programs\Python\Python310\lib\site-packages\yarl\_url.py", line 179, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str

**Comment by DogsTailFarmer** [comment]
Hi!

Probably server can't get correct end-point for initialize WS. Are you init exchanges-wrapper package before first run? 

[init](https://github.com/DogsTailFarmer/martin-binance/wiki/Quick-start#install-from-pip)

Perhaps on Win you must use `Run as admin`, check it for a start pls.

You must get place where config leave in system and put credentials on it.

Regards, Jerry.

**Comment by Lexus083** [comment]
It worked on version 1.3.3. After updating to 1.3.6 this error appeared. 
I removed everything and installed it again - it works.

**Comment by DogsTailFarmer** [comment]
OK, some changes were made to the configuration file, I reported this in the announcement.

[Important notices](https://github.com/DogsTailFarmer/martin-binance#important-notices)
Check there before updates.

Regards, Jerry.
