### ISSUE TITLE
ModuleNotFoundError: No module named 'optimizer'

### ISSUE THREAD

**Issue by DogsTailFarmer** [DogsTailFarmer/martin-binance#73]
when i want to do backtest i have an error, what version of python should i use for this project?: I have 3.10.12
here is my issue:
 martin-binance-backtest
Traceback (most recent call last):
  File "/home/toor/.local/bin/martin-binance-backtest", line 5, in <module>
    from martin_binance.backtest.OoTSP import main
  File "/home/toor/.local/lib/python3.10/site-packages/martin_binance/backtest/OoTSP.py", line 19, in <module>
    from optimizer import optimize
ModuleNotFoundError: No module named 'optimizer'

_Originally posted by @martinbasinski in https://github.com/DogsTailFarmer/martin-binance/discussions/72#discussioncomment-8582930_

**Comment by DogsTailFarmer** [comment]
Fixed in 2.1.5
